{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CharsetEncoding"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/charsetencoding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/charsetencoding"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/SQ","doc:\/\/com.ohmysql.apple.OHMySQL\/SH","doc:\/\/com.ohmysql.apple.OHMySQL\/SY","doc:\/\/com.ohmysql.apple.OHMySQL\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Available character sets."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CharsetEncoding"}],"title":"CharsetEncoding","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@CharsetEncoding","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"CharsetEncoding"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/ASCII","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP1250","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP1251","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP1256","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP850","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP852","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP866","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP932","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/EUCKR","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/GB2312","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/KOI8U","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/KOI8_R","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/SJIS","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UJIS","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF16","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF16LE","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF32","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF8","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF8MB4","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/big5","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/greek","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/hebrew","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin1","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin2","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin5","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin7","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/macRoman"]},{"title":"Initializers","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/Equatable-Implementations","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/EUCKR":{"role":"symbol","title":"CharsetEncoding.EUCKR","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EUCKR"}],"abstract":[{"type":"text","text":"EUC-KR Korean"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/EUCKR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingEUCKR"}],"url":"\/documentation\/ohmysql\/charsetencoding\/euckr"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/latin2":{"role":"symbol","title":"CharsetEncoding.latin2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"latin2"}],"abstract":[{"type":"text","text":"ISO 8859-2 Central European"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingLatin2"}],"url":"\/documentation\/ohmysql\/charsetencoding\/latin2"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ohmysql\/charsetencoding\/rawrepresentable-implementations"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ohmysql\/charsetencoding\/equatable-implementations"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/macRoman":{"role":"symbol","title":"CharsetEncoding.macRoman","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"macRoman"}],"abstract":[{"type":"text","text":"Mac West European"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/macRoman","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingMacRoman"}],"url":"\/documentation\/ohmysql\/charsetencoding\/macroman"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/CP1251":{"role":"symbol","title":"CharsetEncoding.CP1251","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CP1251"}],"abstract":[{"type":"text","text":"Windows Cyrillic"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP1251","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingCP1251"}],"url":"\/documentation\/ohmysql\/charsetencoding\/cp1251"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/UTF8":{"role":"symbol","title":"CharsetEncoding.UTF8","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UTF8"}],"abstract":[{"type":"text","text":"UTF-8 Unicode"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF8","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingUTF8"}],"url":"\/documentation\/ohmysql\/charsetencoding\/utf8"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/CP866":{"role":"symbol","title":"CharsetEncoding.CP866","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CP866"}],"abstract":[{"type":"text","text":"DOS Russian"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP866","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingCP866"}],"url":"\/documentation\/ohmysql\/charsetencoding\/cp866"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/UTF32":{"role":"symbol","title":"CharsetEncoding.UTF32","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UTF32"}],"abstract":[{"type":"text","text":"UTF-32 Unicode"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF32","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingUTF32"}],"url":"\/documentation\/ohmysql\/charsetencoding\/utf32"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/latin1":{"role":"symbol","title":"CharsetEncoding.latin1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"latin1"}],"abstract":[{"type":"text","text":"cp1252 West European"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingLatin1"}],"url":"\/documentation\/ohmysql\/charsetencoding\/latin1"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/CP852":{"role":"symbol","title":"CharsetEncoding.CP852","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CP852"}],"abstract":[{"type":"text","text":"DOS Central European"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP852","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingCP852"}],"url":"\/documentation\/ohmysql\/charsetencoding\/cp852"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/UJIS":{"role":"symbol","title":"CharsetEncoding.UJIS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UJIS"}],"abstract":[{"type":"text","text":"EUC-JP Japanese"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UJIS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingUJIS"}],"url":"\/documentation\/ohmysql\/charsetencoding\/ujis"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/hebrew":{"role":"symbol","title":"CharsetEncoding.hebrew","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hebrew"}],"abstract":[{"type":"text","text":"ISO 8859-8 Hebrew"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/hebrew","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingHebrew"}],"url":"\/documentation\/ohmysql\/charsetencoding\/hebrew"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/KOI8U":{"role":"symbol","title":"CharsetEncoding.KOI8U","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"KOI8U"}],"abstract":[{"type":"text","text":"KOI8-U Ukrainian"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/KOI8U","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingKOI8U"}],"url":"\/documentation\/ohmysql\/charsetencoding\/koi8u"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding":{"role":"symbol","title":"CharsetEncoding","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CharsetEncoding"}],"abstract":[{"type":"text","text":"Available character sets."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncoding"}],"url":"\/documentation\/ohmysql\/charsetencoding"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/ASCII":{"role":"symbol","title":"CharsetEncoding.ASCII","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASCII"}],"abstract":[{"type":"text","text":"US ASCII"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/ASCII","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingASCII"}],"url":"\/documentation\/ohmysql\/charsetencoding\/ascii"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/latin7":{"role":"symbol","title":"CharsetEncoding.latin7","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"latin7"}],"abstract":[{"type":"text","text":"ISO 8859-13 Baltic"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin7","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingLatin7"}],"url":"\/documentation\/ohmysql\/charsetencoding\/latin7"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/big5":{"role":"symbol","title":"CharsetEncoding.big5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"big5"}],"abstract":[{"type":"text","text":"Big5 Traditional Chinese"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/big5","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingBig5"}],"url":"\/documentation\/ohmysql\/charsetencoding\/big5"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/GB2312":{"role":"symbol","title":"CharsetEncoding.GB2312","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GB2312"}],"abstract":[{"type":"text","text":"GB2312 Simplified Chinese"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/GB2312","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingGB2312"}],"url":"\/documentation\/ohmysql\/charsetencoding\/gb2312"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/CP1250":{"role":"symbol","title":"CharsetEncoding.CP1250","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CP1250"}],"abstract":[{"type":"text","text":"Windows Central European"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP1250","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingCP1250"}],"url":"\/documentation\/ohmysql\/charsetencoding\/cp1250"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/latin5":{"role":"symbol","title":"CharsetEncoding.latin5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"latin5"}],"abstract":[{"type":"text","text":"ISO 8859-9 Turkish"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin5","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingLatin5"}],"url":"\/documentation\/ohmysql\/charsetencoding\/latin5"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/SJIS":{"role":"symbol","title":"CharsetEncoding.SJIS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SJIS"}],"abstract":[{"type":"text","text":"Shift-JIS Japanese"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/SJIS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingSJIS"}],"url":"\/documentation\/ohmysql\/charsetencoding\/sjis"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/CP1256":{"role":"symbol","title":"CharsetEncoding.CP1256","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CP1256"}],"abstract":[{"type":"text","text":"Windows Arabic"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP1256","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingCP1256"}],"url":"\/documentation\/ohmysql\/charsetencoding\/cp1256"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/greek":{"role":"symbol","title":"CharsetEncoding.greek","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"greek"}],"abstract":[{"type":"text","text":"ISO 8859-7 Greek"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/greek","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingGreek"}],"url":"\/documentation\/ohmysql\/charsetencoding\/greek"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/CP850":{"role":"symbol","title":"CharsetEncoding.CP850","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CP850"}],"abstract":[{"type":"text","text":"DOS West European"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP850","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingCP850"}],"url":"\/documentation\/ohmysql\/charsetencoding\/cp850"},"doc://com.ohmysql.apple.OHMySQL/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/SY"},"doc://com.ohmysql.apple.OHMySQL/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/SQ"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql\/charsetencoding\/init(rawvalue:)"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/UTF16LE":{"role":"symbol","title":"CharsetEncoding.UTF16LE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UTF16LE"}],"abstract":[{"type":"text","text":"UTF-16LE Unicode"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF16LE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingUTF16LE"}],"url":"\/documentation\/ohmysql\/charsetencoding\/utf16le"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/KOI8_R":{"role":"symbol","title":"CharsetEncoding.KOI8_R","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"KOI8_R"}],"abstract":[{"type":"text","text":"KOI8-R Relcom Russian"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/KOI8_R","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingKOI8_R"}],"url":"\/documentation\/ohmysql\/charsetencoding\/koi8_r"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/UTF8MB4":{"role":"symbol","title":"CharsetEncoding.UTF8MB4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UTF8MB4"}],"abstract":[{"type":"text","text":"UTF-8 Unicode (support emojies)"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF8MB4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingUTF8MB4"}],"url":"\/documentation\/ohmysql\/charsetencoding\/utf8mb4"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/UTF16":{"role":"symbol","title":"CharsetEncoding.UTF16","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UTF16"}],"abstract":[{"type":"text","text":"UTF-16 Unicode"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF16","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingUTF16"}],"url":"\/documentation\/ohmysql\/charsetencoding\/utf16"},"doc://com.ohmysql.apple.OHMySQL/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/s8SendableP"},"doc://com.ohmysql.apple.OHMySQL/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/SH"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/CP932":{"role":"symbol","title":"CharsetEncoding.CP932","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CP932"}],"abstract":[{"type":"text","text":"SJIS for Windows Japanese"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP932","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingCP932"}],"url":"\/documentation\/ohmysql\/charsetencoding\/cp932"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"CharsetEncoding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CharsetEncoding"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CharsetEncoding"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/ASCII","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP1250","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP1251","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP1256","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP850","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP852","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP866","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/CP932","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/EUCKR","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/GB2312","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/KOI8U","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/KOI8_R","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/SJIS","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UJIS","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF16","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF16LE","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF32","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF8","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/UTF8MB4","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/big5","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/greek","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/hebrew","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin1","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin2","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin5","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/latin7","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/macRoman"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CharsetEncoding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1EUCKR\/title","value":"CharsetEncodingEUCKR"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1EUCKR\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingEUCKR"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1latin2\/title","value":"CharsetEncodingLatin2"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1latin2\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingLatin2"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1macRoman\/title","value":"CharsetEncodingMacRoman"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1macRoman\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingMacRoman"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP1251\/title","value":"CharsetEncodingCP1251"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP1251\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingCP1251"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UTF8\/title","value":"CharsetEncodingUTF8"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UTF8\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingUTF8"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP866\/title","value":"CharsetEncodingCP866"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP866\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingCP866"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UTF32\/title","value":"CharsetEncodingUTF32"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UTF32\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingUTF32"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1latin1\/title","value":"CharsetEncodingLatin1"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1latin1\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingLatin1"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP852\/title","value":"CharsetEncodingCP852"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP852\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingCP852"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UJIS\/title","value":"CharsetEncodingUJIS"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UJIS\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingUJIS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1hebrew\/title","value":"CharsetEncodingHebrew"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1hebrew\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingHebrew"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1KOI8U\/title","value":"CharsetEncodingKOI8U"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1KOI8U\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingKOI8U"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding\/title","value":"CharsetEncoding"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding\/fragments","value":[{"kind":"identifier","text":"CharsetEncoding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1ASCII\/title","value":"CharsetEncodingASCII"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1ASCII\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingASCII"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1latin7\/title","value":"CharsetEncodingLatin7"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1latin7\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingLatin7"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1big5\/title","value":"CharsetEncodingBig5"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1big5\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingBig5"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1GB2312\/title","value":"CharsetEncodingGB2312"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1GB2312\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingGB2312"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP1250\/title","value":"CharsetEncodingCP1250"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP1250\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingCP1250"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1latin5\/title","value":"CharsetEncodingLatin5"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1latin5\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingLatin5"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1SJIS\/title","value":"CharsetEncodingSJIS"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1SJIS\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingSJIS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP1256\/title","value":"CharsetEncodingCP1256"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP1256\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingCP1256"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1greek\/title","value":"CharsetEncodingGreek"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1greek\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingGreek"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP850\/title","value":"CharsetEncodingCP850"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP850\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingCP850"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UTF16LE\/title","value":"CharsetEncodingUTF16LE"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UTF16LE\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingUTF16LE"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1KOI8_R\/title","value":"CharsetEncodingKOI8_R"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1KOI8_R\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingKOI8_R"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UTF8MB4\/title","value":"CharsetEncodingUTF8MB4"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UTF8MB4\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingUTF8MB4"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UTF16\/title","value":"CharsetEncodingUTF16"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1UTF16\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingUTF16"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP932\/title","value":"CharsetEncodingCP932"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1CP932\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingCP932"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}