{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"]]},"metadata":{"role":"article","title":"Getting Started","modules":[{"name":"OHMySQL"}],"roleHeading":"Article"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Set up the classes that manage and persist your data.","type":"text"}],"sections":[],"seeAlsoSections":[{"title":"Essentials","generated":true,"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Installation"],"anchor":"Essentials"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ohmysql\/gettingstarted"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ohmysql\/gettingstarted"]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/GettingStarted","interfaceLanguage":"swift"},"primaryContentSections":[{"content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An instance of ","type":"text"},{"code":"OHMySQLConfiguration","type":"codeVoice"},{"text":" represents your connection preferences.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of "},{"type":"reference","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","isActive":true},{"type":"text","text":" manages a connection to the database."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of "},{"type":"codeVoice","code":"OHMySQLQueryContext"},{"type":"text","text":" saves and fetches data from storage, executes the queries."}]}]}]},{"type":"heading","text":"Initialize a Store Coordinator","anchor":"Initialize-a-Store-Coordinator","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Typically, you need to keep only one instance of "},{"type":"reference","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","isActive":true},{"type":"text","text":" in your code. One instance is a one connection."}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Create configuration preference instance:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["let configuration = MySQLConfiguration(userName: \"root\", password: \"root\", serverName: \"localhost\", dbName: \"db_name\", port: 3306, socket: \"\/mysql\/mysql.sock\")"]},{"type":"paragraph","inlineContent":[{"text":"If your connection is configured for SSL, you can specify this at creation:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["let sslConfig = MySQLSSLConfig(key: \"client-key.pem\", certPath: \"client-cert.pem\", certAuthPath: \"ca.pem\", certAuthPEMPath: \"\", cipher: nil)","let configuration = MySQLConfiguration(userName: \"root\", password: \"root\", sslConfig: sslConfig, serverName: \"localhost\", dbName: \"db_name\", port: 3306, socket: \"\/mysql\/mysql.sock\")"]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Create a store coordinator."}]},{"syntax":"swift","type":"codeListing","code":["let coordinator = MySQLStoreCoordinator(user: configuration)"]},{"type":"paragraph","inlineContent":[{"text":"If required, you can set up the encoding and protocol type.","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["coordinator.encoding = .UTF8MB4","coordinator.protocol = .TCP"]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Connect to the database. The method "},{"type":"reference","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/connect()","isActive":true},{"type":"text","text":" returns a boolean value indicating if a connection is set up."}]},{"type":"codeListing","syntax":"swift","code":["if coordinator.connect() {","   print(\"Connected successfully.\")","}"]}]}]},{"type":"heading","text":"Configure Query Context","anchor":"Configure-Query-Context","level":3},{"type":"paragraph","inlineContent":[{"text":"The instance of ","type":"text"},{"type":"codeVoice","code":"OHMySQLQueryContext"},{"text":" is responsible for executing queries, saving\/updating\/deleting model objects. It is a key object in the application.","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"There must be only one ","type":"text"},{"inlineContent":[{"text":"main","type":"text"}],"type":"strong"},{"text":" context in the application.","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["let context = MySQLQueryContext()"],"type":"codeListing"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The context must keep a reference to store coordinator."}]},{"syntax":"swift","type":"codeListing","code":["context.storeCoordinator = coordinator"]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"For your convenience, set a context into singleton of ","type":"text"},{"type":"codeVoice","code":"OHMySQLContainer"},{"text":".","type":"text"}]},{"type":"codeListing","code":["MySQLContainer.shared.mainQueryContext = context"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"You can always access the main context in any place of your code:","type":"text"}]},{"type":"codeListing","code":["MySQLContainer.shared.mainQueryContext?.lastInsertID()"],"syntax":"swift"}]}]},{"type":"heading","text":"Execute Query","anchor":"Execute-Query","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Every query is represented by a string. An instance of "},{"type":"codeVoice","code":"OHMySQLQueryRequest"},{"type":"text","text":" initialized with a string and provides timeline information after execution."}]},{"type":"paragraph","inlineContent":[{"text":"Typically, there are two types of queries.","type":"text"},{"text":" ","type":"text"},{"text":"The first type doesn’t return any result. It executes the query and you can catch the error if any appears.","type":"text"}]},{"syntax":"swift","code":["let queryString = \"DROP TABLE `mytable`\"","let queryRequest = MySQLQueryRequest(queryString: dropQueryString)","","do {","    try MySQLContainer.shared.mainQueryContext?.execute(dropQueryRequest)","} catch {","    print(\"Cannot execute the query.\")","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The second type does return a result. The result is an array of dictionaries."}]},{"syntax":"swift","code":["let queryString = \"SELECT * FROM `mytable`\"","let queryRequest = MySQLQueryRequest(queryString: queryString)","do {","    let result = try MySQLContainer.shared.mainQueryContext?.executeQueryRequestAndFetchResult(query) ?? []","    print(\"\\(result)\")","} catch {","    print(\"Cannot execute the query.\")","}"],"type":"codeListing"}],"kind":"content"}],"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"kind":"symbol","title":"MySQLStoreCoordinator","url":"\/documentation\/ohmysql\/mysqlstorecoordinator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLStoreCoordinator","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","abstract":[{"type":"text","text":"Manages a connection to the database. Stores the configuration and information about a connection."}],"navigatorTitle":[{"text":"MySQLStoreCoordinator","kind":"identifier"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/Installation":{"url":"\/documentation\/ohmysql\/installation","type":"topic","abstract":[{"text":"Learn the ways to integrate the framework in your application.","type":"text"}],"title":"Installation","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Installation","kind":"article","role":"article"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/connect()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"connect()","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/connect()","abstract":[{"text":"Attempts to establish a connection to a MySQL database engine. Also tries establish SSL connection if it is specified.","type":"text"}],"kind":"symbol","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/connect()","role":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"kind":"symbol","url":"\/documentation\/ohmysql","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"role":"collection","title":"OHMySQL","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"generated":true,"anchor":"Essentials","title":"Essentials","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Installation"]}],"path":"\/seeAlsoSections"}]}]}