{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The framework can be installed in different ways."}]},{"anchor":"CocoaPods","level":3,"type":"heading","text":"CocoaPods"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Open "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":" and declare the dependency:"}]},{"type":"codeListing","syntax":"bash","code":["pod 'OHMySQL'"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Then open Terminal, navigate to project folder and install the dependencies:"}]},{"type":"codeListing","syntax":null,"code":["pod install --repo-update"]},{"style":"tip","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Learn how to use "},{"type":"reference","isActive":true,"identifier":"https:\/\/guides.cocoapods.org\/using\/getting-started.html"},{"type":"text","text":"."}]}],"type":"aside","name":"Tip"},{"anchor":"Carthage","level":3,"type":"heading","text":"Carthage"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add the following to your "},{"type":"codeVoice","code":"Cartfile"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"bash","code":["github \"oleghnidets\/OHMySQL\""]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Run the command for updating Carthage dependencies."}]},{"type":"codeListing","syntax":null,"code":["carthage update --use-xcframeworks OHMySQL"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In addition to manually adding xcframework of OHMySQL from "},{"type":"codeVoice","code":"Carthage\/Build"},{"type":"text","text":" folder you will need to add manually "},{"type":"codeVoice","code":"MySQL.xcframework"},{"type":"text","text":". "},{"type":"codeVoice","code":"MySQL.xcframework"},{"type":"text","text":" is a part of this repo, see "},{"type":"codeVoice","code":"OHMySQL\/lib\/MySQL.xcframework"},{"type":"text","text":"."}]},{"style":"tip","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Learn how to use "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/Carthage\/Carthage#quick-start"},{"type":"text","text":"."}]}],"type":"aside","name":"Tip"},{"anchor":"Manually","level":3,"type":"heading","text":"Manually"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Open up Terminal and clone the repo."}]},{"type":"codeListing","syntax":null,"code":["git clone https:\/\/github.com\/oleghnidets\/OHMySQL"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Open cloned repo folder and copy the folder "},{"type":"codeVoice","code":"OHMySQL"},{"type":"text","text":". Paste the folder into your project folder."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Open up your project (xcodeproj) and drag the folder "},{"type":"codeVoice","code":"OHMySQL"},{"type":"text","text":" into the Project Navigator of your application’s Xcode project."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Navigate to the target configuration window and select the application target under the “Targets” heading in the sidebar. In the tab bar at the top of that window, open the “General” panel. Make sure there is the framework "},{"type":"codeVoice","code":"MySQL.xcframework"},{"type":"text","text":" under the “Frameworks & Libraries” section. If not, click on the "},{"type":"codeVoice","code":"+"},{"type":"text","text":" button and add the framework. Also, you will need to add the library "},{"type":"codeVoice","code":"libc++"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/installation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/installation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Installation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Learn the ways to integrate the framework in your application."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Installation","role":"article","modules":[{"name":"OHMySQL"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/GettingStarted"],"generated":true}],"references":{"https://github.com/Carthage/Carthage#quick-start":{"title":"Carthage","titleInlineContent":[{"type":"text","text":"Carthage"}],"type":"link","identifier":"https:\/\/github.com\/Carthage\/Carthage#quick-start","url":"https:\/\/github.com\/Carthage\/Carthage#quick-start"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/GettingStarted":{"role":"article","title":"Getting Started","abstract":[{"type":"text","text":"Set up the classes that manage and persist your data."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/GettingStarted","kind":"article","type":"topic","url":"\/documentation\/ohmysql\/gettingstarted"},"https://guides.cocoapods.org/using/getting-started.html":{"title":"CocoaPods","titleInlineContent":[{"type":"text","text":"CocoaPods"}],"type":"link","identifier":"https:\/\/guides.cocoapods.org\/using\/getting-started.html","url":"https:\/\/guides.cocoapods.org\/using\/getting-started.html"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/GettingStarted"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}