{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStoreCoordinator"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Manages a connection to the database. Stores the configuration and information about a connection."}],"metadata":{"externalID":"c:objc(cs)OHMySQLStoreCoordinator","symbolKind":"class","title":"MySQLStoreCoordinator","role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStoreCoordinator"}],"navigatorTitle":[{"kind":"identifier","text":"MySQLStoreCoordinator"}],"modules":[{"name":"OHMySQL"}]},"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/init(configuration:)"]},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/configuration","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/encoding","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/isConnected","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/protocol","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/store"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/connect()","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/disconnect()","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/pingMySQL()","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/reconnect()","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/refresh(_:)","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/selectDataBase(_:)","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/shutdown()"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/objc(pl)NSObject","doc:\/\/com.ohmysql.apple.OHMySQL\/s7CVarArgP","doc:\/\/com.ohmysql.apple.OHMySQL\/s28CustomDebugStringConvertibleP","doc:\/\/com.ohmysql.apple.OHMySQL\/s23CustomStringConvertibleP","doc:\/\/com.ohmysql.apple.OHMySQL\/SQ","doc:\/\/com.ohmysql.apple.OHMySQL\/SH"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator"]}],"references":{"doc://com.ohmysql.apple.OHMySQL/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/refresh(_:)":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/refresh(_:)","type":"topic","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/refresh(_:)","role":"symbol","abstract":[{"type":"text","text":"Flushes tables or caches, or resets replication server information. The connected user must have the RELOAD privilege."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@OHRefreshOption","text":"RefreshOption"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@OHResultErrorType","text":"ResultErrorType"}],"title":"refresh(_:)","kind":"symbol"},"doc://com.ohmysql.apple.OHMySQL/SQ":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/pingMySQL()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pingMySQL"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@OHResultErrorType","text":"ResultErrorType"}],"title":"pingMySQL()","type":"topic","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/pingmysql()","role":"symbol","abstract":[{"type":"text","text":"Checks whether the connection to the server is working. If the connection has gone down and auto-reconnect is enabled an attempt to reconnect is made."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/pingMySQL()","kind":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/configuration":{"title":"configuration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MySQLConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OHMySQLConfiguration"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Nonnull after connection with DB."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/configuration","kind":"symbol","role":"symbol","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/configuration","type":"topic"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/shutdown()":{"abstract":[{"type":"text","text":"Asks the database server to shut down. The connected user must have the SHUTDOWN privilege."}],"type":"topic","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/shutdown()","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/shutdown()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutdown"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ResultErrorType","preciseIdentifier":"c:@E@OHResultErrorType"}],"kind":"symbol","title":"shutdown()","role":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/OHMySQLStoreCoordinator/mysql":{"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/OHMySQLStoreCoordinator\/mysql","role":"symbol","abstract":[{"type":"text","text":"Nonnull after connection with DB. You don’t need to use this property at all."}],"url":"\/documentation\/ohmysql\/ohmysqlstorecoordinator\/mysql","fragments":[{"text":"mysql","kind":"identifier"}],"kind":"symbol","title":"mysql"},"doc://com.ohmysql.apple.OHMySQL/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/objc(pl)NSObject"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/isConnected":{"kind":"symbol","abstract":[{"text":"Pings the server and indicates whether the connection to the server is working.","type":"text"}],"type":"topic","title":"isConnected","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConnected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/isConnected","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/isconnected"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/encoding":{"type":"topic","kind":"symbol","title":"encoding","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encoding","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@CharsetEncoding","text":"CharsetEncoding","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The default character set for the current connection. By default UTF-8."}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/encoding","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/encoding"},"doc://com.ohmysql.apple.OHMySQL/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/s7CVarArgP","type":"unresolvable"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/disconnect()":{"url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/disconnect()","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/disconnect()","title":"disconnect()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnect"},{"kind":"text","text":"()"}],"kind":"symbol","abstract":[{"text":"Closes a previously opened connection.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"url":"\/documentation\/ohmysql\/mysqlstorecoordinator","kind":"symbol","title":"MySQLStoreCoordinator","abstract":[{"type":"text","text":"Manages a connection to the database. Stores the configuration and information about a connection."}],"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStoreCoordinator"}],"navigatorTitle":[{"kind":"identifier","text":"MySQLStoreCoordinator"}],"role":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/reconnect()":{"url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/reconnect()","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/reconnect()","kind":"symbol","type":"topic","title":"reconnect()","role":"symbol","abstract":[{"type":"text","text":"Attempts to disconnect and then establish a connection to a MySQL database engine. Also tries establish SSL connection if it is specified."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reconnect","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/init(configuration:)":{"title":"init(configuration:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MySQLConfiguration","preciseIdentifier":"c:objc(cs)OHMySQLConfiguration"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/init(configuration:)","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/init(configuration:)","role":"symbol","kind":"symbol","type":"topic","abstract":[]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"abstract":[{"text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS.","type":"text"}],"title":"OHMySQL","type":"topic","role":"collection","url":"\/documentation\/ohmysql","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/protocol":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/protocol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`protocol`","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProtocolType","preciseIdentifier":"c:@E@OHProtocolType","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"protocol","abstract":[{"text":"One of the protocols. Needs to be set before calling -connect.","type":"text"}],"type":"topic","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/protocol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/store":{"title":"store","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MySQLStore","preciseIdentifier":"c:objc(cs)OHMySQLStore"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Nonnull after connection with DB."}],"role":"symbol","kind":"symbol","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/store","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/store","type":"topic"},"doc://com.ohmysql.apple.OHMySQL/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/SH","type":"unresolvable"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/selectDataBase(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Selects new database in scope of current connection."}],"title":"selectDataBase(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/selectDataBase(_:)","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/selectdatabase(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectDataBase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"ResultErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@OHResultErrorType"}]},"doc://com.ohmysql.apple.OHMySQL/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/objc(cs)NSObject","type":"unresolvable"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/connect()":{"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/connect()","title":"connect()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Attempts to establish a connection to a MySQL database engine. Also tries establish SSL connection if it is specified."}],"kind":"symbol","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/connect()"},"doc://com.ohmysql.apple.OHMySQL/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/OHMySQLStoreCoordinator\/mysql"],"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OHMySQLStoreCoordinator"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}}]}]}