{"seeAlsoSections":[{"title":"Setup connection","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLSSLConfig","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLContainer","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLConfiguration"}],"title":"MySQLConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)OHMySQLConfiguration","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"MySQLConfiguration"}]},"abstract":[{"type":"text","text":"The entity that has authority to use a store MySQL."}],"sections":[],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/objc(pl)NSObject","doc:\/\/com.ohmysql.apple.OHMySQL\/s7CVarArgP","doc:\/\/com.ohmysql.apple.OHMySQL\/s28CustomDebugStringConvertibleP","doc:\/\/com.ohmysql.apple.OHMySQL\/s23CustomStringConvertibleP","doc:\/\/com.ohmysql.apple.OHMySQL\/SQ","doc:\/\/com.ohmysql.apple.OHMySQL\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/init(user:password:serverName:dbName:port:socket:)","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/init(user:password:sslConfig:serverName:dbName:port:socket:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/dbName","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/password","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/port","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/readTimeout","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/serverName","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/socket","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/sslConfig","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/username","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/writeTimeout"]}],"variants":[{"paths":["\/documentation\/ohmysql\/mysqlconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/mysqlconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLContainer":{"role":"symbol","title":"MySQLContainer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLContainer"}],"abstract":[{"type":"text","text":"Represents a main context and store coordinator."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLContainer"}],"url":"\/documentation\/ohmysql\/mysqlcontainer"},"doc://com.ohmysql.apple.OHMySQL/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/objc(cs)NSObject"},"doc://com.ohmysql.apple.OHMySQL/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/s28CustomDebugStringConvertibleP"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration/password":{"role":"symbol","title":"password","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"User’ password for authentication. https:\/\/dev.mysql.com\/doc\/refman\/5.5\/en\/password-security-user.html"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/password","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"password"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration\/password"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration/sslConfig":{"role":"symbol","title":"sslConfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sslConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MySQLSSLConfig","preciseIdentifier":"c:objc(cs)OHSSLConfig"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Used for establishing secure connections using SSL."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/sslConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sslConfig"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration\/sslconfig"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration/serverName":{"role":"symbol","title":"serverName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"A host name or an IP address."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/serverName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverName"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration\/servername"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration/dbName":{"role":"symbol","title":"dbName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dbName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The string specifies the name of database."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/dbName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dbName"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration\/dbname"},"doc://com.ohmysql.apple.OHMySQL/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/s7CVarArgP"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration/writeTimeout":{"role":"symbol","title":"writeTimeout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The timeout in seconds for each attempt to write to the server. There is a retry if necessary, so the total effective timeout value is two times the option value."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/writeTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"writeTimeout"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration\/writetimeout"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLSSLConfig":{"role":"symbol","title":"MySQLSSLConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLSSLConfig"}],"abstract":[{"type":"text","text":"This class is used for establishing secure connections using SSL."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLSSLConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLSSLConfig"}],"url":"\/documentation\/ohmysql\/mysqlsslconfig"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration/socket":{"role":"symbol","title":"socket","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"socket"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"If it is not NULL, the string specifies the socket or named pipe to use."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/socket","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"socket"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration\/socket"},"doc://com.ohmysql.apple.OHMySQL/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/SQ"},"doc://com.ohmysql.apple.OHMySQL/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/s23CustomStringConvertibleP"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration/port":{"role":"symbol","title":"port","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"port"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"If it is not 0, the value is used as the port number for the TCP\/IP connection."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/port","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"port"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration\/port"},"doc://com.ohmysql.apple.OHMySQL/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/objc(pl)NSObject"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration/username":{"role":"symbol","title":"username","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Can be up to 16 characters long. Operating system user names may be of a different maximum length."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/username","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"username"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration\/username"},"doc://com.ohmysql.apple.OHMySQL/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/SH"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration":{"role":"symbol","title":"MySQLConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLConfiguration"}],"abstract":[{"type":"text","text":"The entity that has authority to use a store MySQL."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLConfiguration"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryContext":{"role":"symbol","title":"MySQLQueryContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLQueryContext"}],"abstract":[{"type":"text","text":"An instance of this class is responsible for executing queries, saving\/updating\/deleting objects."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLQueryContext"}],"url":"\/documentation\/ohmysql\/mysqlquerycontext"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration/readTimeout":{"role":"symbol","title":"readTimeout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"readTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The timeout in seconds for each attempt to read from the server. There are retries if necessary, so the total effective timeout value is three times the option value. You can set the value so that a lost connection can be detected earlier than the TCP\/IP Close Wait Timeout value of 10 minutes."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/readTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"readTimeout"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration\/readtimeout"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration/init(user:password:serverName:dbName:port:socket:)":{"role":"symbol","title":"init(user:password:serverName:dbName:port:socket:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"serverName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dbName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"port"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socket"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes and returns a newly allocated object."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/init(user:password:serverName:dbName:port:socket:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUser:password:serverName:dbName:port:socket:"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration\/init(user:password:servername:dbname:port:socket:)"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration/init(user:password:sslConfig:serverName:dbName:port:socket:)":{"role":"symbol","title":"init(user:password:sslConfig:serverName:dbName:port:socket:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sslConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MySQLSSLConfig","preciseIdentifier":"c:objc(cs)OHSSLConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"serverName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dbName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"port"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socket"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes and returns a newly allocated object."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/init(user:password:sslConfig:serverName:dbName:port:socket:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUser:password:sslConfig:serverName:dbName:port:socket:"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration\/init(user:password:sslconfig:servername:dbname:port:socket:)"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"role":"symbol","title":"MySQLStoreCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStoreCoordinator"}],"abstract":[{"type":"text","text":"Manages a connection to the database. Stores the configuration and information about a connection."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLStoreCoordinator"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OHMySQLConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OHMySQLConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OHMySQLConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/dbName","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/password","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/port","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/readTimeout","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/serverName","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/socket","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/sslConfig","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/username","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/writeTimeout"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/init(user:password:serverName:dbName:port:socket:)","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration\/init(user:password:sslConfig:serverName:dbName:port:socket:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Setup connection","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLSSLConfig","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLContainer","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OHMySQLConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLContainer\/title","value":"OHMySQLContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLContainer\/fragments","value":[{"kind":"identifier","text":"OHMySQLContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1password\/title","value":"password"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1password\/fragments","value":[{"kind":"identifier","text":"password"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1sslConfig\/title","value":"sslConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1sslConfig\/fragments","value":[{"kind":"identifier","text":"sslConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1serverName\/title","value":"serverName"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1serverName\/fragments","value":[{"kind":"identifier","text":"serverName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1dbName\/title","value":"dbName"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1dbName\/fragments","value":[{"kind":"identifier","text":"dbName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1writeTimeout\/title","value":"writeTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1writeTimeout\/fragments","value":[{"kind":"identifier","text":"writeTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLSSLConfig\/title","value":"OHSSLConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLSSLConfig\/fragments","value":[{"kind":"identifier","text":"OHSSLConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1socket\/title","value":"socket"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1socket\/fragments","value":[{"kind":"identifier","text":"socket"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1port\/title","value":"port"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1port\/fragments","value":[{"kind":"identifier","text":"port"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1username\/title","value":"username"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1username\/fragments","value":[{"kind":"identifier","text":"username"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration\/title","value":"OHMySQLConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration\/fragments","value":[{"kind":"identifier","text":"OHMySQLConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryContext\/title","value":"OHMySQLQueryContext"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryContext\/fragments","value":[{"kind":"identifier","text":"OHMySQLQueryContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1readTimeout\/title","value":"readTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1readTimeout\/fragments","value":[{"kind":"identifier","text":"readTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1init(user:password:serverName:dbName:port:socket:)\/title","value":"initWithUser:password:serverName:dbName:port:socket:"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1init(user:password:serverName:dbName:port:socket:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUser:password:serverName:dbName:port:socket:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1init(user:password:sslConfig:serverName:dbName:port:socket:)\/title","value":"initWithUser:password:sslConfig:serverName:dbName:port:socket:"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration~1init(user:password:sslConfig:serverName:dbName:port:socket:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUser:password:sslConfig:serverName:dbName:port:socket:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/title","value":"OHMySQLStoreCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/fragments","value":[{"kind":"identifier","text":"OHMySQLStoreCoordinator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}