{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSStringEncodingFromCharsetEncoding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"encoding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding","preciseIdentifier":"c:@E@CharsetEncoding","text":"CharsetEncoding"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/nsstringencodingfromcharsetencoding(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/nsstringencodingfromcharsetencoding(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/NSStringEncodingFromCharsetEncoding(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Converts library’ encoding to the Cocoa encoding."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSStringEncodingFromCharsetEncoding"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CharsetEncoding","preciseIdentifier":"c:@E@CharsetEncoding"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"NSStringEncodingFromCharsetEncoding(_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:@F@NSStringEncodingFromCharsetEncoding","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"NSStringEncodingFromCharsetEncoding"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/NSStringEncodingFromCharsetEncoding(_:)":{"role":"symbol","title":"NSStringEncodingFromCharsetEncoding(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSStringEncodingFromCharsetEncoding"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CharsetEncoding","preciseIdentifier":"c:@E@CharsetEncoding"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Converts library’ encoding to the Cocoa encoding."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/NSStringEncodingFromCharsetEncoding(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSStringEncodingFromCharsetEncoding"}],"url":"\/documentation\/ohmysql\/nsstringencodingfromcharsetencoding(_:)"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding":{"role":"symbol","title":"CharsetEncoding","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CharsetEncoding"}],"abstract":[{"type":"text","text":"Available character sets."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncoding"}],"url":"\/documentation\/ohmysql\/charsetencoding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"NSStringEncodingFromCharsetEncoding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NSStringEncodingFromCharsetEncoding"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"NSStringEncoding","preciseIdentifier":"c:@T@NSStringEncoding"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSStringEncodingFromCharsetEncoding"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding","preciseIdentifier":"c:@E@CharsetEncoding","text":"CharsetEncoding"},{"kind":"text","text":" "},{"kind":"internalParam","text":"encoding"},{"kind":"text","text":")"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1NSStringEncodingFromCharsetEncoding(_:)\/title","value":"NSStringEncodingFromCharsetEncoding"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1NSStringEncodingFromCharsetEncoding(_:)\/fragments","value":[{"kind":"identifier","text":"NSStringEncodingFromCharsetEncoding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding\/title","value":"CharsetEncoding"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding\/fragments","value":[{"kind":"identifier","text":"CharsetEncoding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}