{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/refreshoption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/refreshoption"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/SQ","doc:\/\/com.ohmysql.apple.OHMySQL\/SH","doc:\/\/com.ohmysql.apple.OHMySQL\/SY","doc:\/\/com.ohmysql.apple.OHMySQL\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Refresh options."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshOption"}],"title":"RefreshOption","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@OHRefreshOption","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"RefreshOption"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/grant","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/hosts","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/log","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/master","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/none","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/slave","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/status","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/tables","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/threads"]},{"title":"Initializers","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/Equatable-Implementations","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption":{"role":"symbol","title":"RefreshOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshOption"}],"abstract":[{"type":"text","text":"Refresh options."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RefreshOption"}],"url":"\/documentation\/ohmysql\/refreshoption"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ohmysql\/refreshoption\/rawrepresentable-implementations"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/none":{"role":"symbol","title":"RefreshOption.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHRefreshOptionNone"}],"url":"\/documentation\/ohmysql\/refreshoption\/none"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql\/refreshoption\/init(rawvalue:)"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/status":{"role":"symbol","title":"RefreshOption.status","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"}],"abstract":[{"type":"text","text":"Reset status variables, like FLUSH STATUS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/status","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHRefreshOptionStatus"}],"url":"\/documentation\/ohmysql\/refreshoption\/status"},"doc://com.ohmysql.apple.OHMySQL/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/SY"},"doc://com.ohmysql.apple.OHMySQL/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/s8SendableP"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/threads":{"role":"symbol","title":"RefreshOption.threads","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"threads"}],"abstract":[{"type":"text","text":"Flush the thread cache."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/threads","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHRefreshOptionThreads"}],"url":"\/documentation\/ohmysql\/refreshoption\/threads"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ohmysql\/refreshoption\/equatable-implementations"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/hosts":{"role":"symbol","title":"RefreshOption.hosts","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hosts"}],"abstract":[{"type":"text","text":"Flush the host cache, like FLUSH HOSTS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/hosts","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHRefreshOptionHosts"}],"url":"\/documentation\/ohmysql\/refreshoption\/hosts"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/grant":{"role":"symbol","title":"RefreshOption.grant","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"grant"}],"abstract":[{"type":"text","text":"Refresh the grant tables, like FLUSH PRIVILEGES."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/grant","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHRefreshOptionGrant"}],"url":"\/documentation\/ohmysql\/refreshoption\/grant"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/tables":{"role":"symbol","title":"RefreshOption.tables","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tables"}],"abstract":[{"type":"text","text":"Flush the table cache, like FLUSH TABLES."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/tables","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHRefreshOptionTables"}],"url":"\/documentation\/ohmysql\/refreshoption\/tables"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/log":{"role":"symbol","title":"RefreshOption.log","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"log"}],"abstract":[{"type":"text","text":"Flush the logs, like FLUSH LOGS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/log","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHRefreshOptionLog"}],"url":"\/documentation\/ohmysql\/refreshoption\/log"},"doc://com.ohmysql.apple.OHMySQL/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/SH"},"doc://com.ohmysql.apple.OHMySQL/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/SQ"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/slave":{"role":"symbol","title":"RefreshOption.slave","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"slave"}],"abstract":[{"type":"text","text":"On a slave replication server, reset the master server information and restart the slave, like RESET SLAVE."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/slave","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHRefreshOptionSlave"}],"url":"\/documentation\/ohmysql\/refreshoption\/slave"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/master":{"role":"symbol","title":"RefreshOption.master","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"master"}],"abstract":[{"type":"text","text":"On a master replication server, remove the binary log files listed in the binary log index and truncate the index file, like RESET MASTER."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/master","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHRefreshOptionMaster"}],"url":"\/documentation\/ohmysql\/refreshoption\/master"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"OHRefreshOption"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OHRefreshOption"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OHRefreshOption"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/grant","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/hosts","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/log","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/master","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/none","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/slave","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/status","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/tables","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/threads"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OHRefreshOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption\/title","value":"OHRefreshOption"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption\/fragments","value":[{"kind":"identifier","text":"OHRefreshOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1none\/title","value":"OHRefreshOptionNone"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1none\/fragments","value":[{"kind":"identifier","text":"OHRefreshOptionNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1status\/title","value":"OHRefreshOptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1status\/fragments","value":[{"kind":"identifier","text":"OHRefreshOptionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1threads\/title","value":"OHRefreshOptionThreads"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1threads\/fragments","value":[{"kind":"identifier","text":"OHRefreshOptionThreads"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1hosts\/title","value":"OHRefreshOptionHosts"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1hosts\/fragments","value":[{"kind":"identifier","text":"OHRefreshOptionHosts"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1grant\/title","value":"OHRefreshOptionGrant"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1grant\/fragments","value":[{"kind":"identifier","text":"OHRefreshOptionGrant"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1tables\/title","value":"OHRefreshOptionTables"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1tables\/fragments","value":[{"kind":"identifier","text":"OHRefreshOptionTables"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1log\/title","value":"OHRefreshOptionLog"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1log\/fragments","value":[{"kind":"identifier","text":"OHRefreshOptionLog"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1slave\/title","value":"OHRefreshOptionSlave"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1slave\/fragments","value":[{"kind":"identifier","text":"OHRefreshOptionSlave"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1master\/title","value":"OHRefreshOptionMaster"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1master\/fragments","value":[{"kind":"identifier","text":"OHRefreshOptionMaster"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}