{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Join","preciseIdentifier":"c:OHJoinConstants.h@T@OHJoin","text":"Join"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/join\/full"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/join\/full"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Join\/full","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"FULL JOIN"},{"type":"text","text":" type for all matching records from both tables whether the other table matches or not."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Join","preciseIdentifier":"c:OHJoinConstants.h@T@OHJoin"}],"title":"full","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@OHJoinFull","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"OHJoinFull"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Join"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/Join/full":{"role":"symbol","title":"full","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Join","preciseIdentifier":"c:OHJoinConstants.h@T@OHJoin"}],"abstract":[{"type":"codeVoice","code":"FULL JOIN"},{"type":"text","text":" type for all matching records from both tables whether the other table matches or not."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Join\/full","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHJoinFull"}],"url":"\/documentation\/ohmysql\/join\/full"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/Join":{"role":"symbol","title":"Join","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Join"}],"abstract":[],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Join","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Join"}],"url":"\/documentation\/ohmysql\/join"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"OHJoinFull"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OHJoinFull"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"OHJoinFull"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1Join~1full\/title","value":"OHJoinFull"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1Join~1full\/fragments","value":[{"kind":"identifier","text":"OHJoinFull"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1Join\/title","value":"OHJoin"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1Join\/fragments","value":[{"kind":"identifier","text":"OHJoin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}