{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"log"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/refreshoption\/log"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/refreshoption\/log"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/log","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Flush the logs, like FLUSH LOGS."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"log"}],"title":"RefreshOption.log","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OHRefreshOption@OHRefreshOptionLog","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"OHRefreshOptionLog"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption":{"role":"symbol","title":"RefreshOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshOption"}],"abstract":[{"type":"text","text":"Refresh options."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RefreshOption"}],"url":"\/documentation\/ohmysql\/refreshoption"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption/log":{"role":"symbol","title":"RefreshOption.log","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"log"}],"abstract":[{"type":"text","text":"Flush the logs, like FLUSH LOGS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption\/log","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHRefreshOptionLog"}],"url":"\/documentation\/ohmysql\/refreshoption\/log"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OHRefreshOptionLog"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OHRefreshOptionLog"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OHRefreshOptionLog"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption\/title","value":"OHRefreshOption"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption\/fragments","value":[{"kind":"identifier","text":"OHRefreshOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1log\/title","value":"OHRefreshOptionLog"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1RefreshOption~1log\/fragments","value":[{"kind":"identifier","text":"OHRefreshOptionLog"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}