name: OHMySQL
options:
  bundleIdPrefix: com.ohmysql.apple

targetTemplates:
  CommonSettings:
    settings:
      configs:
        debug:
          OTHER_SWIFT_FLAGS: -Wno-incomplete-umbrella
        release:
          OTHER_SWIFT_FLAGS: -Wno-incomplete-umbrella
          
  FrameworkDependencies:
    dependencies:
      - framework: OHMySQL/lib/MySQL.xcframework
      - framework: OHMySQL/lib/OpenSSL.xcframework
      - sdk: Foundation.framework
      - sdk: libc++.tbd

targets:
  OHMySQL:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources: [OHMySQL/Sources, 'OHMySQL.docc']
    scheme: {}
    settings:
      configs:
        debug:
          GENERATE_INFOPLIST_FILE: YES
          DOCC_EXTRACT_SWIFT_INFO_FOR_OBJC_SYMBOLS: YES
        release:
          GENERATE_INFOPLIST_FILE: YES
          DOCC_EXTRACT_SWIFT_INFO_FOR_OBJC_SYMBOLS: YES
    templates:
      - CommonSettings
      - FrameworkDependencies

  OHMySQL-macOS:
    type: framework
    platform: macOS
    deploymentTarget: "11.0"
    sources: [OHMySQL/Sources]
    scheme: {}
    templates:
      - CommonSettings
      - FrameworkDependencies

  OHMySQLTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources: [OHMySQL/Tests]
    settings:
      configs:
        debug:
          GENERATE_INFOPLIST_FILE: YES
        release:
          GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: OHMySQL
