name: OHMySQL
options:
  bundleIdPrefix: com.ohmysql.apple
settings:
  configs:
    debug:
      OTHER_SWIFT_FLAGS: -Wno-incomplete-umbrella
    release:
      OTHER_SWIFT_FLAGS: -Wno-incomplete-umbrella

targets:
  OHMySQL:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources: [OHMySQL/Sources, 'OHMySQL.docc']
    scheme: {}
    settings:
      configs:
        debug:
          GENERATE_INFOPLIST_FILE: YES
          DOCC_EXTRACT_SWIFT_INFO_FOR_OBJC_SYMBOLS: YES
        release:
          GENERATE_INFOPLIST_FILE: YES
          DOCC_EXTRACT_SWIFT_INFO_FOR_OBJC_SYMBOLS: YES
    dependencies:
      - framework: OHMySQL/lib/MySQL.xcframework
      - sdk: Foundation.framework
      - sdk: libc++.tbd

  OHMySQL-macOS:
    type: framework
    platform: macOS
    deploymentTarget: "11.0"
    sources: [OHMySQL/Sources]
    scheme: {}
    dependencies:
      - framework: OHMySQL/lib/MySQL.xcframework
      - sdk: Foundation.framework
      - sdk: libc++.tbd
