name: OHMySQL
options:
  bundleIdPrefix: com.ohmysql.apple

targetTemplates:
  CommonSettings:
    settings:
      configs:
        debug:
          OTHER_SWIFT_FLAGS: -Wno-incomplete-umbrella
        release:
          OTHER_SWIFT_FLAGS: -Wno-incomplete-umbrella
          
  FrameworkDependencies:
    dependencies:
      - framework: OHMySQL/lib/MySQL.xcframework
      - framework: OHMySQL/lib/OpenSSL.xcframework
      - sdk: Foundation.framework
      - sdk: libc++.tbd
  EnvVariables:
    scheme:
      environmentVariables:
          DB_HOST: "$(DB_HOST)"
          DB_NAME: "$(DB_NAME)"
          DB_PORT: "$(DB_PORT)"
          DB_SOCKET: "$(DB_SOCKET)"
          USER_NAME: "$(USER_NAME)"

targets:
  OHMySQL:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources: [OHMySQL/Sources, 'OHMySQL.docc']
    scheme: 
      testTargets:
        - OHMySQLTests
    settings:
      configs:
        debug:
          GENERATE_INFOPLIST_FILE: YES
          DOCC_EXTRACT_SWIFT_INFO_FOR_OBJC_SYMBOLS: YES
        release:
          GENERATE_INFOPLIST_FILE: YES
          DOCC_EXTRACT_SWIFT_INFO_FOR_OBJC_SYMBOLS: YES
    templates:
      - CommonSettings
      - FrameworkDependencies
      - EnvVariables

  OHMySQL-macOS:
    type: framework
    platform: macOS
    deploymentTarget: "11.0"
    sources: [OHMySQL/Sources]
    scheme: {}
    templates:
      - CommonSettings
      - FrameworkDependencies
      - EnvVariables

  OHMySQLTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources: [OHMySQL/Tests]
    scheme:
      test:
        config: Debug
        targets:
          - name: OHMySQLTests
            parallelizable: true
            randomExecutionOrder: true
    settings:
      configs:
        debug:
          GENERATE_INFOPLIST_FILE: YES
        release:
          GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: OHMySQL
    templates:
      - EnvVariables
