{"abstract":[{"text":"Nonnull after connection with DB. You don’t need to use this property at all.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"mysql","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst"]}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/OHMySQLStoreCoordinator\/mysql"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ohmysql\/ohmysqlstorecoordinator\/mysql"]}],"metadata":{"role":"symbol","externalID":"c:objc(cs)OHMySQLStoreCoordinator(py)mysql","modules":[{"name":"OHMySQL"}],"symbolKind":"property","title":"mysql","fragments":[{"kind":"identifier","text":"mysql"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"mysql"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"kind":"symbol","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"url":"\/documentation\/ohmysql","role":"collection","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","abstract":[{"text":"Manages a connection to the database. Stores the configuration and information about a connection.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MySQLStoreCoordinator","kind":"identifier"}],"kind":"symbol","title":"MySQLStoreCoordinator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLStoreCoordinator","kind":"identifier"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/OHMySQLStoreCoordinator/mysql":{"fragments":[{"kind":"identifier","text":"mysql"}],"abstract":[{"type":"text","text":"Nonnull after connection with DB. You don’t need to use this property at all."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/OHMySQLStoreCoordinator\/mysql","url":"\/documentation\/ohmysql\/ohmysqlstorecoordinator\/mysql","type":"topic","kind":"symbol","title":"mysql","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/title","op":"replace","value":"OHMySQLStoreCoordinator"},{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/fragments","op":"replace","value":[{"text":"OHMySQLStoreCoordinator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/navigatorTitle","op":"replace","value":[{"text":"OHMySQLStoreCoordinator","kind":"identifier"}]}]}]}