{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serializationDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CFAbsoluteTime","preciseIdentifier":"c:@T@CFAbsoluteTime"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/mysqlquerytimeline\/serializationduration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/mysqlquerytimeline\/serializationduration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryTimeline\/serializationDuration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The time when the serialization was completed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serializationDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CFAbsoluteTime","preciseIdentifier":"c:@T@CFAbsoluteTime"}],"title":"serializationDuration","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)OHMySQLQueryTimeline(py)serializationDuration","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"serializationDuration"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryTimeline"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryTimeline/serializationDuration":{"role":"symbol","title":"serializationDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serializationDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CFAbsoluteTime","preciseIdentifier":"c:@T@CFAbsoluteTime"}],"abstract":[{"type":"text","text":"The time when the serialization was completed."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryTimeline\/serializationDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serializationDuration"}],"url":"\/documentation\/ohmysql\/mysqlquerytimeline\/serializationduration"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryTimeline":{"role":"symbol","title":"MySQLQueryTimeline","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLQueryTimeline"}],"abstract":[{"type":"text","text":"An instance of OHMySQLTimeline represents lifecycle of the query."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryTimeline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLQueryTimeline"}],"url":"\/documentation\/ohmysql\/mysqlquerytimeline"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"serializationDuration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"serializationDuration"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CFAbsoluteTime","preciseIdentifier":"c:@T@CFAbsoluteTime"},{"kind":"text","text":" "},{"kind":"identifier","text":"serializationDuration"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryTimeline~1serializationDuration\/title","value":"serializationDuration"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryTimeline~1serializationDuration\/fragments","value":[{"kind":"identifier","text":"serializationDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryTimeline\/title","value":"OHMySQLQueryTimeline"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryTimeline\/fragments","value":[{"kind":"identifier","text":"OHMySQLQueryTimeline"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}