{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"},"topicSections":[{"anchor":"Essentials","title":"Essentials","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Installation","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/GettingStarted"]},{"anchor":"Setup-connection","title":"Setup connection","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]},{"anchor":"Classes","title":"Classes","generated":true,"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLContainer","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequest","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequestFactory","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryTimeline","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLSSLConfig","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStore"]},{"anchor":"Protocols","title":"Protocols","generated":true,"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLMappingProtocol"]},{"anchor":"Structures","title":"Structures","generated":true,"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Join"]},{"anchor":"Functions","title":"Functions","generated":true,"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLCharsetForEncoding(_:)","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/NSStringEncodingFromCharsetEncoding(_:)"]},{"anchor":"Enumerations","title":"Enumerations","generated":true,"identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ProtocolType","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType"]}],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"Overview","type":"heading"},{"inlineContent":[{"text":"OHMySQL can connect to remote or local MySQL database and execute CRUD operations. The framework is built upon MySQL C API, but you don’t need to dive into low-level.","type":"text"},{"text":" ","type":"text"},{"text":"The following diagram represents a general architecture. Logic (saving, editing, removing etc.) is aggregated in the app. The database is just a shared storage.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"identifier":"diagram.png","type":"image"}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ohmysql"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ohmysql"]}],"hierarchy":{"paths":[[]]},"abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"metadata":{"role":"collection","roleHeading":"Framework","externalID":"OHMySQL","modules":[{"name":"OHMySQL"}],"title":"OHMySQL","symbolKind":"module"},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/NSStringEncodingFromCharsetEncoding(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStringEncodingFromCharsetEncoding","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CharsetEncoding","kind":"typeIdentifier","preciseIdentifier":"c:@E@CharsetEncoding"},{"text":") -> ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/ohmysql\/nsstringencodingfromcharsetencoding(_:)","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/NSStringEncodingFromCharsetEncoding(_:)","abstract":[],"title":"NSStringEncodingFromCharsetEncoding(_:)","kind":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration":{"abstract":[],"navigatorTitle":[{"text":"MySQLConfiguration","kind":"identifier"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLConfiguration","kind":"identifier"}],"title":"MySQLConfiguration","type":"topic","role":"symbol","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryRequest":{"role":"symbol","title":"MySQLQueryRequest","url":"\/documentation\/ohmysql\/mysqlqueryrequest","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLQueryRequest"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequest","navigatorTitle":[{"kind":"identifier","text":"MySQLQueryRequest"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/ResultErrorType":{"type":"topic","url":"\/documentation\/ohmysql\/resulterrortype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"ResultErrorType"}],"title":"ResultErrorType","kind":"symbol","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","role":"symbol","abstract":[]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption":{"kind":"symbol","abstract":[],"title":"RefreshOption","url":"\/documentation\/ohmysql\/refreshoption","role":"symbol","navigatorTitle":[{"text":"RefreshOption","kind":"identifier"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RefreshOption","kind":"identifier"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLSSLConfig":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLSSLConfig","kind":"identifier"}],"type":"topic","url":"\/documentation\/ohmysql\/mysqlsslconfig","kind":"symbol","title":"MySQLSSLConfig","role":"symbol","abstract":[],"navigatorTitle":[{"text":"MySQLSSLConfig","kind":"identifier"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLSSLConfig"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/Join":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Join","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Join"}],"navigatorTitle":[{"kind":"identifier","text":"Join"}],"url":"\/documentation\/ohmysql\/join","abstract":[],"title":"Join"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/ProtocolType":{"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ProtocolType","kind":"identifier"}],"title":"ProtocolType","url":"\/documentation\/ohmysql\/protocoltype","navigatorTitle":[{"text":"ProtocolType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ProtocolType"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryTimeline":{"url":"\/documentation\/ohmysql\/mysqlquerytimeline","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLQueryTimeline","kind":"identifier"}],"navigatorTitle":[{"text":"MySQLQueryTimeline","kind":"identifier"}],"title":"MySQLQueryTimeline","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryTimeline","abstract":[],"type":"topic","role":"symbol"},"diagram.png":{"type":"image","alt":"Simple Diagram","variants":[{"url":"\/images\/com.ohmysql.apple.OHMySQL\/diagram.png","traits":["1x","light"]}],"identifier":"diagram.png"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryContext":{"url":"\/documentation\/ohmysql\/mysqlquerycontext","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext","title":"MySQLQueryContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLQueryContext","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MySQLQueryContext","kind":"identifier"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryRequestFactory":{"role":"symbol","abstract":[],"url":"\/documentation\/ohmysql\/mysqlqueryrequestfactory","type":"topic","kind":"symbol","title":"MySQLQueryRequestFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLQueryRequestFactory"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequestFactory","navigatorTitle":[{"kind":"identifier","text":"MySQLQueryRequestFactory"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLMappingProtocol":{"abstract":[],"title":"MySQLMappingProtocol","url":"\/documentation\/ohmysql\/mysqlmappingprotocol","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLMappingProtocol","navigatorTitle":[{"kind":"identifier","text":"MySQLMappingProtocol"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLMappingProtocol"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLContainer":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLContainer","kind":"identifier"}],"navigatorTitle":[{"text":"MySQLContainer","kind":"identifier"}],"url":"\/documentation\/ohmysql\/mysqlcontainer","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLContainer","abstract":[],"title":"MySQLContainer","kind":"symbol","type":"topic","role":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/OHSerialization":{"fragments":[{"text":"OHSerialization","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","kind":"symbol","title":"OHSerialization","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/OHSerialization","url":"\/documentation\/ohmysql\/ohserialization"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStore":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStore"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MySQLStore"}],"type":"topic","title":"MySQLStore","role":"symbol","url":"\/documentation\/ohmysql\/mysqlstore","abstract":[],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStore"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"kind":"symbol","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"url":"\/documentation\/ohmysql","role":"collection","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/GettingStarted":{"url":"\/documentation\/ohmysql\/gettingstarted","kind":"article","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/GettingStarted","abstract":[{"type":"text","text":"Set up the classes that manage and persist your data."}],"title":"Getting Started","role":"article"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding","abstract":[],"url":"\/documentation\/ohmysql\/charsetencoding","navigatorTitle":[{"text":"CharsetEncoding","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CharsetEncoding","kind":"identifier"}],"title":"CharsetEncoding"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLCharsetForEncoding(_:)":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLCharsetForEncoding","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CharsetEncoding","preciseIdentifier":"c:@E@CharsetEncoding","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLCharsetForEncoding(_:)","abstract":[],"url":"\/documentation\/ohmysql\/mysqlcharsetforencoding(_:)","title":"MySQLCharsetForEncoding(_:)"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/Installation":{"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Installation","abstract":[{"text":"Learn the ways to integrate the framework in your application.","type":"text"}],"url":"\/documentation\/ohmysql\/installation","title":"Installation","role":"article","kind":"article"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","abstract":[{"text":"Manages a connection to the database. Stores the configuration and information about a connection.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MySQLStoreCoordinator","kind":"identifier"}],"kind":"symbol","title":"MySQLStoreCoordinator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLStoreCoordinator","kind":"identifier"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"anchor":"Essentials","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Installation","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/GettingStarted"],"title":"Essentials"},{"anchor":"Setup-connection","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"],"title":"Setup connection"},{"anchor":"Protocols","identifiers":["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/OHSerialization"],"title":"Protocols","generated":true}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"OHMySQLStoreCoordinator","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OHMySQLStoreCoordinator"}],"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OHMySQLStoreCoordinator"}],"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/navigatorTitle"}]}]}