{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASCII"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/charsetencoding\/ascii"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/charsetencoding\/ascii"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/ASCII","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"US ASCII"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASCII"}],"title":"CharsetEncoding.ASCII","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@CharsetEncoding@CharsetEncodingASCII","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingASCII"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding":{"role":"symbol","title":"CharsetEncoding","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CharsetEncoding"}],"abstract":[{"type":"text","text":"Available character sets."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncoding"}],"url":"\/documentation\/ohmysql\/charsetencoding"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/ASCII":{"role":"symbol","title":"CharsetEncoding.ASCII","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASCII"}],"abstract":[{"type":"text","text":"US ASCII"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/ASCII","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingASCII"}],"url":"\/documentation\/ohmysql\/charsetencoding\/ascii"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CharsetEncodingASCII"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingASCII"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CharsetEncodingASCII"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding\/title","value":"CharsetEncoding"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding\/fragments","value":[{"kind":"identifier","text":"CharsetEncoding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1ASCII\/title","value":"CharsetEncodingASCII"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1ASCII\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingASCII"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}