{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SJIS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/charsetencoding\/sjis"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/charsetencoding\/sjis"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/SJIS","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shift-JIS Japanese"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SJIS"}],"title":"CharsetEncoding.SJIS","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@CharsetEncoding@CharsetEncodingSJIS","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingSJIS"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding/SJIS":{"role":"symbol","title":"CharsetEncoding.SJIS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SJIS"}],"abstract":[{"type":"text","text":"Shift-JIS Japanese"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding\/SJIS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncodingSJIS"}],"url":"\/documentation\/ohmysql\/charsetencoding\/sjis"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding":{"role":"symbol","title":"CharsetEncoding","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CharsetEncoding"}],"abstract":[{"type":"text","text":"Available character sets."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CharsetEncoding"}],"url":"\/documentation\/ohmysql\/charsetencoding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CharsetEncodingSJIS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingSJIS"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CharsetEncodingSJIS"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1SJIS\/title","value":"CharsetEncodingSJIS"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding~1SJIS\/fragments","value":[{"kind":"identifier","text":"CharsetEncodingSJIS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding\/title","value":"CharsetEncoding"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1CharsetEncoding\/fragments","value":[{"kind":"identifier","text":"CharsetEncoding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}