{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMySQL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mysql"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/mysqlstore\/initwithmysql:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStore\/initWithMySQL:","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMySQL:"}],"title":"initWithMySQL:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)OHMySQLStore(im)initWithMySQL:","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMySQL:"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStore"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStore":{"role":"symbol","title":"MySQLStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStore"}],"abstract":[{"type":"text","text":"An object of this class contains details about a store MySQL."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLStore"}],"url":"\/documentation\/ohmysql\/mysqlstore"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStore/initWithMySQL:":{"role":"symbol","title":"initWithMySQL:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMySQL:"}],"abstract":[],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStore\/initWithMySQL:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMySQL:"}],"url":"\/documentation\/ohmysql\/mysqlstore\/initwithmysql:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStore\/title","value":"OHMySQLStore"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStore\/fragments","value":[{"kind":"identifier","text":"OHMySQLStore"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}