{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"affectedRows"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Zero"},{"type":"text","text":" indicates that no records were updated for an "},{"type":"codeVoice","code":"UPDATE"},{"type":"text","text":" statement, no rows matched the "},{"type":"codeVoice","code":"WHERE"},{"type":"text","text":" clause in the query or that no query has yet been executed. "},{"type":"codeVoice","code":"-1"},{"type":"text","text":" indicates that the query returned an error."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/mysqlquerycontext\/affectedrows()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/mysqlquerycontext\/affectedrows()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext\/affectedRows()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns an integer greater than zero indicates the number of rows affected or retrieved."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"affectedRows"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"title":"affectedRows()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)OHMySQLQueryContext(im)affectedRows","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"affectedRows"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryContext/affectedRows()":{"role":"symbol","title":"affectedRows()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"affectedRows"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns an integer greater than zero indicates the number of rows affected or retrieved."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext\/affectedRows()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"affectedRows"}],"url":"\/documentation\/ohmysql\/mysqlquerycontext\/affectedrows()"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryContext":{"role":"symbol","title":"MySQLQueryContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLQueryContext"}],"abstract":[{"type":"text","text":"An instance of this class is responsible for executing queries, saving\/updating\/deleting objects."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLQueryContext"}],"url":"\/documentation\/ohmysql\/mysqlquerycontext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"affectedRows"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"affectedRows"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"affectedRows"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryContext~1affectedRows()\/title","value":"affectedRows"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryContext~1affectedRows()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"affectedRows"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryContext\/title","value":"OHMySQLQueryContext"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryContext\/fragments","value":[{"kind":"identifier","text":"OHMySQLQueryContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}