{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastInsertID"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"0"},{"type":"text","text":", which reflects that no row was inserted. Or returns "},{"type":"codeVoice","code":"0"},{"type":"text","text":" if the previous statement does not use an "},{"type":"codeVoice","code":"AUTO_INCREMENT"},{"type":"text","text":" value."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/mysqlquerycontext\/lastinsertid()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/mysqlquerycontext\/lastinsertid()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext\/lastInsertID()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a value representing the first automatically generated value that was set for an "},{"type":"codeVoice","code":"AUTO_INCREMENT"},{"type":"text","text":" column by the most recently executed "},{"type":"codeVoice","code":"INSERT"},{"type":"text","text":" statement to affect such a column."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastInsertID"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"title":"lastInsertID()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)OHMySQLQueryContext(im)lastInsertID","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"lastInsertID"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryContext/lastInsertID()":{"role":"symbol","title":"lastInsertID()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastInsertID"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"abstract":[{"type":"text","text":"Returns a value representing the first automatically generated value that was set for an "},{"type":"codeVoice","code":"AUTO_INCREMENT"},{"type":"text","text":" column by the most recently executed "},{"type":"codeVoice","code":"INSERT"},{"type":"text","text":" statement to affect such a column."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext\/lastInsertID()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lastInsertID"}],"url":"\/documentation\/ohmysql\/mysqlquerycontext\/lastinsertid()"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryContext":{"role":"symbol","title":"MySQLQueryContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLQueryContext"}],"abstract":[{"type":"text","text":"An instance of this class is responsible for executing queries, saving\/updating\/deleting objects."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLQueryContext"}],"url":"\/documentation\/ohmysql\/mysqlquerycontext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"lastInsertID"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lastInsertID"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"lastInsertID"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryContext~1lastInsertID()\/title","value":"lastInsertID"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryContext~1lastInsertID()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lastInsertID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryContext\/title","value":"OHMySQLQueryContext"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryContext\/fragments","value":[{"kind":"identifier","text":"OHMySQLQueryContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}