{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/protocoltype\/default"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/protocoltype\/default"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ProtocolType\/default","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Default connection."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"title":"ProtocolType.default","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OHProtocolType@OHProtocolTypeDefault","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"OHProtocolTypeDefault"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ProtocolType"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/ProtocolType":{"role":"symbol","title":"ProtocolType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProtocolType"}],"abstract":[{"type":"text","text":"Represents protocol types that can be used during session."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ProtocolType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProtocolType"}],"url":"\/documentation\/ohmysql\/protocoltype"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/ProtocolType/default":{"role":"symbol","title":"ProtocolType.default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[{"type":"text","text":"Default connection."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ProtocolType\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHProtocolTypeDefault"}],"url":"\/documentation\/ohmysql\/protocoltype\/default"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OHProtocolTypeDefault"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OHProtocolTypeDefault"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OHProtocolTypeDefault"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1ProtocolType\/title","value":"OHProtocolType"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1ProtocolType\/fragments","value":[{"kind":"identifier","text":"OHProtocolType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1ProtocolType~1default\/title","value":"OHProtocolTypeDefault"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1ProtocolType~1default\/fragments","value":[{"kind":"identifier","text":"OHProtocolTypeDefault"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}