{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/resulterrortype\/unknowncode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/resulterrortype\/unknowncode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType\/unknownCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An unknown error code received. Look at debug console."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownCode"}],"title":"ResultErrorType.unknownCode","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OHResultErrorType@OHResultErrorTypeUnknownCode","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"OHResultErrorTypeUnknownCode"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/ResultErrorType":{"role":"symbol","title":"ResultErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultErrorType"}],"abstract":[{"type":"text","text":"Client error codes and messages."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultErrorType"}],"url":"\/documentation\/ohmysql\/resulterrortype"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/ResultErrorType/unknownCode":{"role":"symbol","title":"ResultErrorType.unknownCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownCode"}],"abstract":[{"type":"text","text":"An unknown error code received. Look at debug console."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType\/unknownCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OHResultErrorTypeUnknownCode"}],"url":"\/documentation\/ohmysql\/resulterrortype\/unknowncode"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OHResultErrorTypeUnknownCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OHResultErrorTypeUnknownCode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OHResultErrorTypeUnknownCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1ResultErrorType\/title","value":"OHResultErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1ResultErrorType\/fragments","value":[{"kind":"identifier","text":"OHResultErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1ResultErrorType~1unknownCode\/title","value":"OHResultErrorTypeUnknownCode"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1ResultErrorType~1unknownCode\/fragments","value":[{"kind":"identifier","text":"OHResultErrorTypeUnknownCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}