{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"joinType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromTable"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"columnNames"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"joinOn"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequest","preciseIdentifier":"c:objc(cs)OHMySQLQueryRequest","text":"MySQLQueryRequest"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"joinType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Type of join (Use one of the constants from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Join"},{"type":"text","text":")."}]}]},{"name":"tableName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Name of the target table."}]}]},{"name":"columnNames","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Columns to fetch."}]}]},{"name":"joinOn","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In format "},{"type":"codeVoice","code":"[Table:Condition]"},{"type":"text","text":". Example: "},{"type":"codeVoice","code":"{ \"Users\":\"Users.id=Company.userId\" }"},{"type":"text","text":"."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/mysqlqueryrequestfactory\/jointype(_:fromtable:columnnames:joinon:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/mysqlqueryrequestfactory\/jointype(_:fromtable:columnnames:joinon:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequestFactory\/joinType(_:fromTable:columnNames:joinOn:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Combines rows from two or more tables, based on a common field between them."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromTable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"columnNames"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"joinOn"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"MySQLQueryRequest","preciseIdentifier":"c:objc(cs)OHMySQLQueryRequest"}],"title":"joinType(_:fromTable:columnNames:joinOn:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)OHMySQLQueryRequestFactory(cm)JOINType:fromTable:columnNames:joinOn:","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"JOINType:fromTable:columnNames:joinOn:"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequestFactory"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryRequest":{"role":"symbol","title":"MySQLQueryRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLQueryRequest"}],"abstract":[{"type":"text","text":"An instance of OHMySQLQueryRequest describes SQL query used to retrieve data from a MySQL store."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLQueryRequest"}],"url":"\/documentation\/ohmysql\/mysqlqueryrequest"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryRequestFactory":{"role":"symbol","title":"MySQLQueryRequestFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLQueryRequestFactory"}],"abstract":[{"type":"text","text":"Convenience class for making specific "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequest"},{"type":"text","text":" instances."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequestFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLQueryRequestFactory"}],"url":"\/documentation\/ohmysql\/mysqlqueryrequestfactory"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/Join":{"role":"symbol","title":"Join","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Join"}],"abstract":[],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/Join","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Join"}],"url":"\/documentation\/ohmysql\/join"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLQueryRequestFactory/joinType(_:fromTable:columnNames:joinOn:)":{"role":"symbol","title":"joinType(_:fromTable:columnNames:joinOn:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromTable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"columnNames"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"joinOn"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"MySQLQueryRequest","preciseIdentifier":"c:objc(cs)OHMySQLQueryRequest"}],"abstract":[{"type":"text","text":"Combines rows from two or more tables, based on a common field between them."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequestFactory\/joinType(_:fromTable:columnNames:joinOn:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JOINType:fromTable:columnNames:joinOn:"}],"url":"\/documentation\/ohmysql\/mysqlqueryrequestfactory\/jointype(_:fromtable:columnnames:joinon:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"JOINType:fromTable:columnNames:joinOn:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"JOINType:fromTable:columnNames:joinOn:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLQueryRequest","preciseIdentifier":"c:objc(cs)OHMySQLQueryRequest","text":"OHMySQLQueryRequest"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"JOINType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"joinType"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromTable:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tableName"},{"kind":"text","text":" "},{"kind":"identifier","text":"columnNames:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"columnNames"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinOn:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"joinOn"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryRequest\/title","value":"OHMySQLQueryRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryRequest\/fragments","value":[{"kind":"identifier","text":"OHMySQLQueryRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryRequestFactory\/title","value":"OHMySQLQueryRequestFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryRequestFactory\/fragments","value":[{"kind":"identifier","text":"OHMySQLQueryRequestFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1Join\/title","value":"OHJoin"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1Join\/fragments","value":[{"kind":"identifier","text":"OHJoin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryRequestFactory~1joinType(_:fromTable:columnNames:joinOn:)\/title","value":"JOINType:fromTable:columnNames:joinOn:"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLQueryRequestFactory~1joinType(_:fromTable:columnNames:joinOn:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"JOINType:fromTable:columnNames:joinOn:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}