platform :ios, '14.0'
use_frameworks!

def shared_pods 
	pod 'OHMySQL', :path => '../'
end

target 'OHMySQL' do
   shared_pods
end

target 'OHMySQLTests' do
   shared_pods
end

target 'OHMySQLDemo' do
   shared_pods
end
