
use_frameworks!

def mainPods 
	pod 'OHMySQL', :path => '../'
#:git => 'https://github.com/oleghnidets/OHMySQL', :branch => 'develop'
end

target 'OHMySQL' do
   mainPods
end

target 'OHMySQLTests' do
   mainPods
end