
use_frameworks!

def mainPods 
	pod 'OHMySQL', :git => 'https://github.com/oleghnidets/OHMySQL', :branch => 'develop-experiment'
end

target 'OHMySQL' do
   mainPods
end

target 'OHMySQLTests' do
   mainPods
end