{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration","preciseIdentifier":"c:objc(cs)OHMySQLConfiguration","text":"MySQLConfiguration"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/configuration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/configuration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/configuration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Nonnull after connection with DB."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MySQLConfiguration","preciseIdentifier":"c:objc(cs)OHMySQLConfiguration"},{"kind":"text","text":"?"}],"title":"configuration","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)OHMySQLStoreCoordinator(py)configuration","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"configuration"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration":{"role":"symbol","title":"MySQLConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLConfiguration"}],"abstract":[{"type":"text","text":"The entity that has authority to use a store MySQL."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLConfiguration"}],"url":"\/documentation\/ohmysql\/mysqlconfiguration"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/configuration":{"role":"symbol","title":"configuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MySQLConfiguration","preciseIdentifier":"c:objc(cs)OHMySQLConfiguration"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Nonnull after connection with DB."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/configuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/configuration"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"role":"symbol","title":"MySQLStoreCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStoreCoordinator"}],"abstract":[{"type":"text","text":"Manages a connection to the database. Stores the configuration and information about a connection."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLStoreCoordinator"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"configuration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"configuration"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration","preciseIdentifier":"c:objc(cs)OHMySQLConfiguration","text":"OHMySQLConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"configuration"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration\/title","value":"OHMySQLConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLConfiguration\/fragments","value":[{"kind":"identifier","text":"OHMySQLConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator~1configuration\/title","value":"configuration"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator~1configuration\/fragments","value":[{"kind":"identifier","text":"configuration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/title","value":"OHMySQLStoreCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/fragments","value":[{"kind":"identifier","text":"OHMySQLStoreCoordinator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}