{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/connect()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/connect()"]}],"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/connect()"},"abstract":[{"text":"Attempts to establish a connection to a MySQL database engine. Also tries establish SSL connection if it is specified.","type":"text"}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"OHMySQL"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"connect"}],"externalID":"c:objc(cs)OHMySQLStoreCoordinator(im)connect","title":"connect()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connect","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","abstract":[{"text":"Manages a connection to the database. Stores the configuration and information about a connection.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MySQLStoreCoordinator","kind":"identifier"}],"kind":"symbol","title":"MySQLStoreCoordinator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLStoreCoordinator","kind":"identifier"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/connect()":{"navigatorTitle":[{"text":"connect","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connect","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"connect()","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/connect()","role":"symbol","abstract":[{"text":"Attempts to establish a connection to a MySQL database engine. Also tries establish SSL connection if it is specified.","type":"text"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/connect()","kind":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"kind":"symbol","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"url":"\/documentation\/ohmysql","role":"collection","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"connect"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"connect"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"connect","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/title","op":"replace","value":"OHMySQLStoreCoordinator"},{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/fragments","op":"replace","value":[{"text":"OHMySQLStoreCoordinator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OHMySQLStoreCoordinator"}]},{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator~1connect()\/title","op":"replace","value":"connect"},{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator~1connect()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"connect","kind":"identifier"}]}]}]}