{"metadata":{"roleHeading":"Instance Property","title":"encoding","externalID":"c:objc(cs)OHMySQLStoreCoordinator(py)encoding","symbolKind":"property","role":"symbol","modules":[{"name":"OHMySQL"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoding"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CharsetEncoding","kind":"typeIdentifier","text":"CharsetEncoding"}]},"variants":[{"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/encoding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/encoding"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoding"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CharsetEncoding","kind":"typeIdentifier","text":"CharsetEncoding","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/encoding","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"abstract":[{"type":"text","text":"The default character set for the current connection. By default UTF-8."}],"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLStoreCoordinator","kind":"identifier"}],"type":"topic","title":"MySQLStoreCoordinator","abstract":[{"text":"Manages a connection to the database. Stores the configuration and information about a connection.","type":"text"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MySQLStoreCoordinator","kind":"identifier"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/CharsetEncoding":{"url":"\/documentation\/ohmysql\/charsetencoding","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CharsetEncoding","kind":"identifier"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding","type":"topic","kind":"symbol","navigatorTitle":[{"text":"CharsetEncoding","kind":"identifier"}],"role":"symbol","title":"CharsetEncoding"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/encoding":{"abstract":[{"text":"The default character set for the current connection. By default UTF-8.","type":"text"}],"kind":"symbol","title":"encoding","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/encoding","type":"topic","role":"symbol","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/encoding","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encoding","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CharsetEncoding","kind":"typeIdentifier","preciseIdentifier":"c:@E@CharsetEncoding"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","type":"topic","role":"collection","kind":"symbol","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"url":"\/documentation\/ohmysql"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/CharsetEncoding","preciseIdentifier":"c:@E@CharsetEncoding","text":"CharsetEncoding"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoding"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"}]}]}