{"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/init(configuration:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration","preciseIdentifier":"c:objc(cs)OHMySQLConfiguration","text":"MySQLConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"variants":[{"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/init(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/init(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"metadata":{"roleHeading":"Initializer","externalID":"c:objc(cs)OHMySQLStoreCoordinator(im)initWithConfiguration:","symbolKind":"init","role":"symbol","title":"init(configuration:)","modules":[{"name":"OHMySQL"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MySQLConfiguration","preciseIdentifier":"c:objc(cs)OHMySQLConfiguration"},{"kind":"text","text":")"}]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"url":"\/documentation\/ohmysql\/mysqlstorecoordinator","kind":"symbol","title":"MySQLStoreCoordinator","abstract":[{"type":"text","text":"Manages a connection to the database. Stores the configuration and information about a connection."}],"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStoreCoordinator"}],"navigatorTitle":[{"kind":"identifier","text":"MySQLStoreCoordinator"}],"role":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLConfiguration":{"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/ohmysql\/mysqlconfiguration","title":"MySQLConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"MySQLConfiguration"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/init(configuration:)":{"title":"init(configuration:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MySQLConfiguration","preciseIdentifier":"c:objc(cs)OHMySQLConfiguration"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/init(configuration:)","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/init(configuration:)","role":"symbol","kind":"symbol","type":"topic","abstract":[]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"abstract":[{"text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS.","type":"text"}],"title":"OHMySQL","type":"topic","role":"collection","url":"\/documentation\/ohmysql","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLConfiguration","text":"OHMySQLConfiguration","preciseIdentifier":"c:objc(cs)OHMySQLConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"}],"traits":[{"interfaceLanguage":"occ"}]}]}