{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isConnected","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Pings the server and indicates whether the connection to the server is working.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/isconnected"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/isconnected"]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"OHMySQL"}],"title":"isConnected","externalID":"c:objc(cs)OHMySQLStoreCoordinator(py)connected","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isConnected","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/isConnected"},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLStoreCoordinator","kind":"identifier"}],"type":"topic","title":"MySQLStoreCoordinator","abstract":[{"text":"Manages a connection to the database. Stores the configuration and information about a connection.","type":"text"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MySQLStoreCoordinator","kind":"identifier"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","type":"topic","role":"collection","kind":"symbol","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/isConnected":{"role":"symbol","abstract":[{"text":"Pings the server and indicates whether the connection to the server is working.","type":"text"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/isconnected","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/isConnected","kind":"symbol","title":"isConnected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConnected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isConnected","kind":"identifier"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"}]}]}