{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mysql"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/mysql"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/mysql","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Nonnull after connection with DB. You don’t need to use this property at all."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"mysql"}],"title":"mysql","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)OHMySQLStoreCoordinator(py)mysql","modules":[{"name":"OHMySQL"}],"navigatorTitle":[{"kind":"identifier","text":"mysql"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"role":"collection","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/mysql":{"role":"symbol","title":"mysql","fragments":[{"kind":"identifier","text":"mysql"}],"abstract":[{"type":"text","text":"Nonnull after connection with DB. You don’t need to use this property at all."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/mysql","kind":"symbol","type":"topic","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/mysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"role":"symbol","title":"MySQLStoreCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStoreCoordinator"}],"abstract":[{"type":"text","text":"Manages a connection to the database. Stores the configuration and information about a connection."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MySQLStoreCoordinator"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/title","value":"OHMySQLStoreCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/fragments","value":[{"kind":"identifier","text":"OHMySQLStoreCoordinator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}