{"variants":[{"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/pingmysql()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/pingmysql()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Checks whether the connection to the server is working. If the connection has gone down and auto-reconnect is enabled an attempt to reconnect is made."}],"kind":"symbol","metadata":{"title":"pingMySQL()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pingMySQL","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ResultErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@OHResultErrorType"}],"role":"symbol","externalID":"c:objc(cs)OHMySQLStoreCoordinator(im)pingMySQL","roleHeading":"Instance Method","modules":[{"name":"OHMySQL"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pingMySQL"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@OHResultErrorType","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","text":"ResultErrorType"}],"platforms":["Mac Catalyst"]}]},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"Zero if the connection to the server is active. Nonzero if an error occurred. A nonzero return does not indicate whether the MySQL server itself is down; the connection might be broken for other reasons such as network problems.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/pingMySQL()"},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/ResultErrorType":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultErrorType"}],"url":"\/documentation\/ohmysql\/resulterrortype","abstract":[],"title":"ResultErrorType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ResultErrorType"}],"type":"topic"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"abstract":[{"text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS.","type":"text"}],"title":"OHMySQL","type":"topic","role":"collection","url":"\/documentation\/ohmysql","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"url":"\/documentation\/ohmysql\/mysqlstorecoordinator","kind":"symbol","title":"MySQLStoreCoordinator","abstract":[{"type":"text","text":"Manages a connection to the database. Stores the configuration and information about a connection."}],"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStoreCoordinator"}],"navigatorTitle":[{"kind":"identifier","text":"MySQLStoreCoordinator"}],"role":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/pingMySQL()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pingMySQL"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@OHResultErrorType","text":"ResultErrorType"}],"title":"pingMySQL()","type":"topic","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/pingmysql()","role":"symbol","abstract":[{"type":"text","text":"Checks whether the connection to the server is working. If the connection has gone down and auto-reconnect is enabled an attempt to reconnect is made."}],"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/pingMySQL()","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"OHResultErrorType","preciseIdentifier":"c:@E@OHResultErrorType","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pingMySQL","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"Zero if the connection to the server is active. Nonzero if an error occurred. A nonzero return does not indicate whether the MySQL server itself is down; the connection might be broken for other reasons such as network problems.","type":"text"}],"type":"paragraph"}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}