{"abstract":[{"type":"text","text":"One of the protocols. Needs to be set before calling -connect."}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/protocol","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/protocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/protocol"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`protocol`"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProtocolType","preciseIdentifier":"c:@E@OHProtocolType","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ProtocolType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","externalID":"c:objc(cs)OHMySQLStoreCoordinator(py)protocol","role":"symbol","title":"protocol","roleHeading":"Instance Property","modules":[{"name":"OHMySQL"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`protocol`"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@OHProtocolType","text":"ProtocolType"}]},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLStoreCoordinator","kind":"identifier"}],"type":"topic","title":"MySQLStoreCoordinator","abstract":[{"text":"Manages a connection to the database. Stores the configuration and information about a connection.","type":"text"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MySQLStoreCoordinator","kind":"identifier"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/ProtocolType":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ProtocolType","abstract":[],"role":"symbol","url":"\/documentation\/ohmysql\/protocoltype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProtocolType","kind":"identifier"}],"title":"ProtocolType","kind":"symbol","navigatorTitle":[{"text":"ProtocolType","kind":"identifier"}],"type":"topic"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/protocol":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/protocol","abstract":[{"text":"One of the protocols. Needs to be set before calling -connect.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/protocol","title":"protocol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`protocol`","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProtocolType","kind":"typeIdentifier","preciseIdentifier":"c:@E@OHProtocolType"}],"type":"topic"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","type":"topic","role":"collection","kind":"symbol","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"url":"\/documentation\/ohmysql"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ProtocolType","preciseIdentifier":"c:@E@OHProtocolType","text":"OHProtocolType"},{"kind":"text","text":" "},{"kind":"identifier","text":"protocol"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}}]}]}