{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reconnect","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/reconnect()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/reconnect()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/reconnect()"]}],"abstract":[{"text":"Attempts to disconnect and then establish a connection to a MySQL database engine. Also tries establish SSL connection if it is specified.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"OHMySQL"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reconnect","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(cs)OHMySQLStoreCoordinator(im)reconnect","navigatorTitle":[{"text":"reconnect","kind":"identifier"}],"role":"symbol","title":"reconnect()","roleHeading":"Instance Method"},"kind":"symbol","sections":[],"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"kind":"symbol","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"url":"\/documentation\/ohmysql","role":"collection","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","abstract":[{"text":"Manages a connection to the database. Stores the configuration and information about a connection.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MySQLStoreCoordinator","kind":"identifier"}],"kind":"symbol","title":"MySQLStoreCoordinator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLStoreCoordinator","kind":"identifier"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/reconnect()":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/reconnect()","role":"symbol","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/reconnect()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnect"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"reconnect"}],"abstract":[{"type":"text","text":"Attempts to disconnect and then establish a connection to a MySQL database engine. Also tries establish SSL connection if it is specified."}],"title":"reconnect()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"reconnect","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reconnect","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"reconnect"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OHMySQLStoreCoordinator","path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/title"},{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/fragments","op":"replace","value":[{"text":"OHMySQLStoreCoordinator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OHMySQLStoreCoordinator"}]},{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator~1reconnect()\/title","op":"replace","value":"reconnect"},{"path":"\/references\/doc:~1~1com.ohmysql.apple.OHMySQL~1documentation~1OHMySQL~1MySQLStoreCoordinator~1reconnect()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reconnect"}]}]}]}