{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"text":"Flushes tables or caches, or resets replication server information. The connected user must have the RELOAD privilege.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/refresh(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/refresh(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OHRefreshOption","kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption","text":"RefreshOption"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@OHResultErrorType","kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","text":"ResultErrorType"}],"languages":["swift"],"platforms":["Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"name":"options","content":[{"inlineContent":[{"type":"text","text":"A bit mask composed from any combination."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"Zero for success. Nonzero if an error occurred (see ","type":"text"},{"code":"OHResultErrorType","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/refresh(_:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@OHRefreshOption","text":"RefreshOption","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@OHResultErrorType","text":"ResultErrorType","kind":"typeIdentifier"}],"role":"symbol","title":"refresh(_:)","symbolKind":"method","externalID":"c:objc(cs)OHMySQLStoreCoordinator(im)refresh:","modules":[{"name":"OHMySQL"}]},"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"sections":[],"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLStoreCoordinator","kind":"identifier"}],"type":"topic","title":"MySQLStoreCoordinator","abstract":[{"text":"Manages a connection to the database. Stores the configuration and information about a connection.","type":"text"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MySQLStoreCoordinator","kind":"identifier"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/RefreshOption":{"url":"\/documentation\/ohmysql\/refreshoption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshOption"}],"navigatorTitle":[{"kind":"identifier","text":"RefreshOption"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption","type":"topic","kind":"symbol","title":"RefreshOption"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/ResultErrorType":{"role":"symbol","url":"\/documentation\/ohmysql\/resulterrortype","kind":"symbol","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultErrorType","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ResultErrorType","kind":"identifier"}],"type":"topic","title":"ResultErrorType"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","type":"topic","role":"collection","kind":"symbol","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/refresh(_:)":{"kind":"symbol","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/refresh(_:)","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/refresh(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RefreshOption","preciseIdentifier":"c:@E@OHRefreshOption","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"ResultErrorType","preciseIdentifier":"c:@E@OHResultErrorType","kind":"typeIdentifier"}],"title":"refresh(_:)","abstract":[{"type":"text","text":"Flushes tables or caches, or resets replication server information. The connected user must have the RELOAD privilege."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","preciseIdentifier":"c:@E@OHResultErrorType","kind":"typeIdentifier","text":"OHResultErrorType"},{"kind":"text","text":") "},{"kind":"identifier","text":"refresh:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/RefreshOption","preciseIdentifier":"c:@E@OHRefreshOption","kind":"typeIdentifier","text":"OHRefreshOption"},{"kind":"text","text":") "},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A bit mask composed from any combination."}],"type":"paragraph"}],"name":"options"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"Zero for success. Nonzero if an error occurred (see ","type":"text"},{"code":"OHResultErrorType","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"}],"traits":[{"interfaceLanguage":"occ"}]}]}