{"metadata":{"modules":[{"name":"OHMySQL"}],"title":"selectDataBase(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectDataBase"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ResultErrorType","preciseIdentifier":"c:@E@OHResultErrorType"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)OHMySQLStoreCoordinator(im)selectDataBase:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/selectdatabase(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/selectdatabase(_:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Selects new database in scope of current connection.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectDataBase"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"database"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","text":"ResultErrorType","preciseIdentifier":"c:@E@OHResultErrorType"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Name of the target db.","type":"text"}]}],"name":"database"}]},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"Zero for success. Nonzero if an error occurred (see "},{"type":"codeVoice","code":"OHResultErrorType"},{"type":"text","text":")."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/selectDataBase(_:)","interfaceLanguage":"swift"},"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/selectDataBase(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Selects new database in scope of current connection."}],"title":"selectDataBase(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/selectDataBase(_:)","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/selectdatabase(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectDataBase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"ResultErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@OHResultErrorType"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/ResultErrorType":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultErrorType"}],"url":"\/documentation\/ohmysql\/resulterrortype","abstract":[],"title":"ResultErrorType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ResultErrorType"}],"type":"topic"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"url":"\/documentation\/ohmysql\/mysqlstorecoordinator","kind":"symbol","title":"MySQLStoreCoordinator","abstract":[{"type":"text","text":"Manages a connection to the database. Stores the configuration and information about a connection."}],"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStoreCoordinator"}],"navigatorTitle":[{"kind":"identifier","text":"MySQLStoreCoordinator"}],"role":"symbol"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"abstract":[{"text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS.","type":"text"}],"title":"OHMySQL","type":"topic","role":"collection","url":"\/documentation\/ohmysql","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@E@OHResultErrorType","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","kind":"typeIdentifier","text":"OHResultErrorType"},{"kind":"text","text":") "},{"kind":"identifier","text":"selectDataBase:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"database"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Name of the target db."}],"type":"paragraph"}],"name":"database"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"Zero for success. Nonzero if an error occurred (see "},{"code":"OHResultErrorType","type":"codeVoice"},{"type":"text","text":")."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}