{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Asks the database server to shut down. The connected user must have the SHUTDOWN privilege."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutdown"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","preciseIdentifier":"c:@E@OHResultErrorType","kind":"typeIdentifier","text":"ResultErrorType"}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"Zero for success. Nonzero if an error occurred (see ","type":"text"},{"code":"OHResultErrorType","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"metadata":{"title":"shutdown()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutdown"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@E@OHResultErrorType","kind":"typeIdentifier","text":"ResultErrorType"}],"modules":[{"name":"OHMySQL"}],"externalID":"c:objc(cs)OHMySQLStoreCoordinator(im)shutdown","roleHeading":"Instance Method","symbolKind":"method","role":"symbol"},"identifier":{"url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/shutdown()","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/shutdown()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/shutdown()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLStoreCoordinator","kind":"identifier"}],"type":"topic","title":"MySQLStoreCoordinator","abstract":[{"text":"Manages a connection to the database. Stores the configuration and information about a connection.","type":"text"}],"url":"\/documentation\/ohmysql\/mysqlstorecoordinator","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MySQLStoreCoordinator","kind":"identifier"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/ResultErrorType":{"role":"symbol","url":"\/documentation\/ohmysql\/resulterrortype","kind":"symbol","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultErrorType","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ResultErrorType","kind":"identifier"}],"type":"topic","title":"ResultErrorType"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","type":"topic","role":"collection","kind":"symbol","title":"OHMySQL","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"url":"\/documentation\/ohmysql"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/shutdown()":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Asks the database server to shut down. The connected user must have the SHUTDOWN privilege."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutdown"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ResultErrorType","preciseIdentifier":"c:@E@OHResultErrorType"}],"title":"shutdown()","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/shutdown()","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/shutdown()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/ResultErrorType","preciseIdentifier":"c:@E@OHResultErrorType","text":"OHResultErrorType"},{"kind":"text","text":") "},{"kind":"identifier","text":"shutdown"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"Zero for success. Nonzero if an error occurred (see "},{"type":"codeVoice","code":"OHResultErrorType"},{"type":"text","text":")."}],"type":"paragraph"}],"kind":"content"}}]}]}