{"kind":"symbol","metadata":{"title":"store","symbolKind":"property","externalID":"c:objc(cs)OHMySQLStoreCoordinator(py)store","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"store","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)OHMySQLStore","text":"MySQLStore","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"OHMySQL"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStore","preciseIdentifier":"c:objc(cs)OHMySQLStore","kind":"typeIdentifier","text":"MySQLStore"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/store"},"abstract":[{"type":"text","text":"Nonnull after connection with DB."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/store"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ohmysql\/mysqlstorecoordinator\/store"]}],"hierarchy":{"paths":[["doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL","doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator"]]},"sections":[],"references":{"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL":{"kind":"symbol","url":"\/documentation\/ohmysql","abstract":[{"type":"text","text":"The framework allows to establish a connection with MySQL database. The framework supports Objective-C and Swift, iOS, macOS, Catalyst, tvOS, watchOS."}],"role":"collection","title":"OHMySQL","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL"},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator":{"kind":"symbol","title":"MySQLStoreCoordinator","url":"\/documentation\/ohmysql\/mysqlstorecoordinator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MySQLStoreCoordinator","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator","abstract":[{"type":"text","text":"Manages a connection to the database. Stores the configuration and information about a connection."}],"navigatorTitle":[{"text":"MySQLStoreCoordinator","kind":"identifier"}]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStore":{"title":"MySQLStore","url":"\/documentation\/ohmysql\/mysqlstore","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MySQLStore"}],"kind":"symbol","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStore","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MySQLStore"}],"abstract":[]},"doc://com.ohmysql.apple.OHMySQL/documentation/OHMySQL/MySQLStoreCoordinator/store":{"title":"store","type":"topic","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStoreCoordinator\/store","url":"\/documentation\/ohmysql\/mysqlstorecoordinator\/store","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"store","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MySQLStore","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OHMySQLStore"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Nonnull after connection with DB."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ohmysql.apple.OHMySQL\/documentation\/OHMySQL\/MySQLStore","preciseIdentifier":"c:objc(cs)OHMySQLStore","text":"OHMySQLStore"},{"kind":"text","text":" * "},{"kind":"identifier","text":"store"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}}]}]}